airsoft/airsoft/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include("homepage.urls")),
    path("teams/", include("airsoft_teams.urls")),

    path('registration/', include("airsoft_registration.urls")),

    path('organization/', include("airsoft_organization.urls")),
    path('events/', include("airsoft_event.urls")),
    path('shops/', include("airsoft_shops.urls")),
    path("admin/", admin.site.urls),
    path('auth/', include("u_auth.urls")),


    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




# admin if debug
if settings.DEBUG:
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

airsoft/airsoft_event/urls.py
import django.urls
from airsoft_registration.views import TeamRegistrationView, TeamVoteRegistrationView
from .views import EventListVies, EventDetails


app_name = "airsoft_event"
urlpatterns = [
    # path("create/", EventCreateViews.as_view(), name="create_event"),
    # path("create/", EventCreateViews.as_view(), include("airsoft_organization.urls")),
    django.urls.path("", EventListVies.as_view(), name="events"),
    django.urls.path("<int:pk>", EventDetails.as_view(), name="event"),
    django.urls.path("<int:pk>/registration",
                     TeamRegistrationView.as_view(),
                     name="team_reg"),  # airsoft_registration
    django.urls.path("<int:pk>/registration_by_vote",
                     TeamVoteRegistrationView.as_view(),
                     name="team_reg_vote"),

        ]

airsoft/airsoft_teams/urls.py
# pylint: disable=too-many-ancestors
# pylint: disable=missing-module-docstring
# pylint: disable=missing-class-docstring
# pylint: disable=missing-function-docstring
from django.urls import path

from . import views
from .views import TeamListView, TeamCreate, TeamDetails, PostCreateView, TeamMemberDetails

app_name = "airsoft_teams"
urlpatterns = [
    path("", TeamListView.as_view(), name="teams"),
    path("create/", TeamCreate.as_view(), name="create"),
    path("<int:pk>/", TeamMemberDetails.as_view(), name="team"),
    path("<int:pk>/view", TeamDetails.as_view(), name="team_view"),
    path("<int:pk>/post/", PostCreateView.as_view(), name="post_create"),

    path('<int:team_pk>/member_manager/<int:member_pk>/',
         views.member_manager,
         name='member_manager'),

    path('<int:team_pk>/request_manager/<int:request_pk>/',
         views.request_manager,
         name='request_manager'),

]

airsoft/u_auth/urls.py
# pylint: disable=too-many-ancestors
# pylint: disable=missing-module-docstring
# pylint: disable=missing-class-docstring
# pylint: disable=missing-function-docstring
from django.urls import path

from .views import (
    MeView,
    LoginView,
    LogoutView,
    UserCreateView
    )

app_name = "u_auth"

urlpatterns = [

    path("me/", MeView.as_view(), name="me"),
    # path("me/edit", MeView.as_view(), name="me"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register", UserCreateView.as_view(), name="register")

]

airsoft/airsoft_event/models.py
from typing import TYPE_CHECKING

from django.db import models

# Create your models here.
from django.urls import reverse


class Event(models.Model):
    name = models.CharField(max_length=128,
                            blank=False,
                            null=False,
                            unique=True
                            )
    owner = models.ForeignKey("airsoft_organization.Organization",
                              on_delete=models.PROTECT,
                              related_name="event_owner"
                              )
    polygon = models.ForeignKey("airsoft_polygon.Polygon",
                                on_delete=models.PROTECT,
                                blank=True, null=True
                                )
    Description = models.TextField(blank=True, null=True)
    banner = models.ImageField(upload_to='event_banner',
                               blank=True,
                               default='nopic.jpeg'
                               )
    arrival_date = models.DateField()
    start_date = models.DateField()
    end_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    edited_at = models.DateTimeField(auto_now=True)
    # slug = models.SlugField(max_length=255, unique=True,
    # db_index=True,
    # verbose_name="URL"
    # )
    registration_open = models.BooleanField(default=False)
    solo_allowed = models.BooleanField(default=False)

    if TYPE_CHECKING:
        objects: models.Manager

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(f'/event/{self.pk}')


class Sides(models.Model):

    name = models.CharField(max_length=128)
    hidden_scenario = models.BooleanField(default=False)
    scenario = models.ForeignKey("airsoft_event.Scenario",
                                 on_delete=models.CASCADE,
                                 blank=True, null=True)

    def __str__(self):
        return self.name

class Scenario(models.Model):
    body = models.TextField()

airsoft/airsoft_event/forms.py
from django import forms
from .models import Event

class EventCreateForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ("name",
                  "polygon",
                  "Description",
                  "banner",
                  "arrival_date",
                  "start_date",
                  "end_date")

airsoft/airsoft_event/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
# Create your views here.
from django.views.generic import CreateView, ListView, DetailView

from airsoft_organization.models import Organization, Member
from airsoft_registration.models import EventVote

from .forms import EventCreateForm
from .models import Event


class EventCreateViews(CreateView):
    model = Event
    form_class = EventCreateForm
    template_name = "event_create.html"

    def form_valid(self, form):
        member = get_object_or_404(Member, pk=self.kwargs["pk"], user=self.request.user)
        if Organization.can_create_event(member.org, member):
            obj = form.save(commit=False)
            obj.owner = member.org
            obj.save()
            return HttpResponseRedirect(f'/events/{obj.id}')
        # else:
        #     return HttpResponseRedirect(f'/organization/{self.kwargs["pk"]}')


class EventListVies(ListView):
    paginate_by = 14
    context_object_name = "events"
    template_name = "events.html"
    model = Event
    queryset = Event.objects.all()


class EventDetails(DetailView):
    context_object_name = "event"
    template_name = 'event_details.html'
    queryset = Event.objects.prefetch_related("registered_teams")
    def post(self, request, *args, **kwargs, ):
        if request.method == 'POST':
            for key, value in request.POST.items():
                print(f'Key:{key}', key)
                print(f'Value:{value}', value)
            print(self.kwargs)
            print(self.args)
            event = get_object_or_404(Event, pk=self.kwargs["pk"])
            if request.POST.get("vote"):
                EventVote.objects.get_or_create(event=event,
                                                team=self.request.user.team_profile.team)

                return HttpResponseRedirect(f'/events/{event.id}')
        print(str(event))
        return HttpResponseRedirect(f'/events/{event.id}')

airsoft/airsoft_event/templates/event_create.html
{% extends 'homepage/base.html' %}

{% block title %}
Creat Team

{% endblock %}

{% block body %}

<form method="post" >
    {% csrf_token %}
    {{ form.as_p }}

    <button class="btn btn-outline-secondary btn-sm" type="submit" name="team" value="team" >Creat</button>
     <a href="{% url 'airsoft_teams:teams' %}" class="btn btn-outline-secondary btn-sm">Back</a>
</form>


{% endblock %}

{% block content %}


<!-- Button trigger modal -->






{% endblock %}

airsoft/airsoft_event/templates/event_details.html
{% extends 'homepage/base.html' %}


{% block title %}
Organization
{% endblock %}

{% block body %}
<p>Organization :</p>
<li class="list-group-item">city - {{event.city}}</li>
<li class="list-group-item">описание - {{event.description}}</li>
<li class="list-group-item">name - {{event.name}}</li>
<li class="list-group-item">owner - {{event.owner}}</li>
<li class="list-group-item">id - {{event.id}}</li>
<li class="list-group-item">id - {{event.created_at}}</li>
<li class="list-group-item">id - {{event.edited_at}}</li>
<li class="list-group-item">id - {{event.is_private}}</li>




<div>
<form method="post">
    {% csrf_token %}
    <button class="btn btn-outline-secondary btn-sm" name="vote" value="vote"  type="submit"> vote </button>
</form>

<a href="{% url 'airsoft_event:team_reg' event.pk %}" class="btn btn-outline-secondary btn-sm">reg</a>

</div>

registration
{% for teams in event.registered_teams.all%}

<li class="list-group-item"> team - {{ teams }} {{ teams.side }}</li>
{% endfor %}

{% endblock %}

airsoft/airsoft_event/templates/events.html
{% extends 'homepage/base.html' %}




{% block title %} some shit{% endblock %}

{% block body %}

<div class="row row-cols-1 row-cols-md-6 g-4">
{% for event in events %}
<div class="col">
    <div class="card h-100">
      <img src={{ event.banner.url }} class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">{{ event.name }}</h5>
        <p class="card-text">{{ event.description }}</p>
      <a class="stretched-link" href="{% url 'airsoft_event:event' event.pk %}"></a>
      </div>
    </div>

</div>

{% endfor %}
</div>
<div class="pagination">
    <span class="step-links">
        {% if event.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ event.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ event.number }} of {{ event.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ event.next_page_number }}">next</a>
            <a href="?page={{ event.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

{% block content %}





{% endblock %}