airsoft/airsoft/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include("homepage.urls")),
    path("teams/", include("airsoft_teams.urls")),

    path('registration/', include("airsoft_registration.urls")),

    path('organization/', include("airsoft_organization.urls")),
    path('events/', include("airsoft_event.urls")),
    path('shops/', include("airsoft_shops.urls")),
    path("admin/", admin.site.urls),
    path('auth/', include("u_auth.urls")),


    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




# admin if debug
if settings.DEBUG:
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

airsoft/airsoft_teams/urls.py
# pylint: disable=too-many-ancestors
# pylint: disable=missing-module-docstring
# pylint: disable=missing-class-docstring
# pylint: disable=missing-function-docstring
from django.urls import path

from . import views
from .views import TeamListView, TeamCreate, TeamDetails, PostCreateView, TeamMemberDetails

app_name = "airsoft_teams"
urlpatterns = [
    path("", TeamListView.as_view(), name="teams"),
    path("create/", TeamCreate.as_view(), name="create"),
    path("<int:pk>/", TeamMemberDetails.as_view(), name="team"),
    path("<int:pk>/view", TeamDetails.as_view(), name="team_view"),
    path("<int:pk>/post/", PostCreateView.as_view(), name="post_create"),

    path('<int:team_pk>/member_manager/<int:member_pk>/',
         views.member_manager,
         name='member_manager'),

    path('<int:team_pk>/request_manager/<int:request_pk>/',
         views.request_manager,
         name='request_manager'),

]

airsoft/u_auth/urls.py
# pylint: disable=too-many-ancestors
# pylint: disable=missing-module-docstring
# pylint: disable=missing-class-docstring
# pylint: disable=missing-function-docstring
from django.urls import path

from .views import (
    MeView,
    LoginView,
    LogoutView,
    UserCreateView
    )

app_name = "u_auth"

urlpatterns = [

    path("me/", MeView.as_view(), name="me"),
    # path("me/edit", MeView.as_view(), name="me"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register", UserCreateView.as_view(), name="register")

]

airsoft/airsoft_teams/models.py
# pylint: disable=too-many-ancestors
# pylint: disable=missing-module-docstring
# pylint: disable=missing-class-docstring
# pylint: disable=missing-function-docstring


from typing import TYPE_CHECKING

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from guardian.shortcuts import assign_perm

# Create your models here.

UserModel: AbstractUser = get_user_model()


class TeamMember(models.Model):
    RECRUIT = 1
    MEMBER = 2
    MANAGER = 3
    OWNER = 4
    ROLE_CHOICES = (
        (RECRUIT, 'recruit'),
        (MEMBER, 'member'),
        (MANAGER, 'manager'),
        (OWNER, 'owner'),

    )
    team = models.ForeignKey("airsoft_teams.Team",
                             on_delete=models.CASCADE,
                             related_name="team_member"
                             )
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE,
                                related_name="team_profile"
                                )
    created_at = models.DateTimeField(auto_now_add=True)
    edited_at = models.DateTimeField(auto_now=True)
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, default=RECRUIT)

    def __str__(self):
        return self.user.username

    def request_handler(self, key, value):

        if key == "role":
            if 1 <= int(value) <= 4:  # set_owner up change for 3
                self.set_role(role=value)
                return self
        if key == "kick":
            self.kick()
            return self

    def set_owner(self):
        self.role = 4
        self.save()
        assign_perm('g_view_team', self.user, self.team)
        assign_perm('g_create_team_post', self.user, self.team)
        assign_perm('g_team_member_manager', self.user, self.team)
        assign_perm('g_team_vote', self.user, self.team)
        return self

    def set_role(self, role):
        """make role groups"""
        self.role = role
        self.save()

        if role == 4:
            print("set role owner")
        if role == 3:
            print("set role manager")
            assign_perm('g_team_member_manager', self.user, self.team)
        if role == 2:
            print("set role member")
        if role == 1:
            print("set role rec")
        return self

    def kick(self):
        self.delete()


class Team(models.Model):
    name = models.CharField(max_length=64, blank=False, null=False, unique=True)
    city = models.CharField(max_length=64, blank=False, null=False)
    description = models.TextField()
    chevron = models.ImageField(upload_to='chevron/', blank=True, default='nopic.jpeg')
    pattern = models.ManyToManyField("airsoft_gear.Pattern", blank=True, default='nopic.jpeg')
    members = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="member",
                                     through="airsoft_teams.TeamMember")
    # frends = models.ManyToManyField(settings.AUTH_USER_MODEL,
    # related_name="frends" ,
    # through="airsoft_teams.Team_Frends")
    created_at = models.DateTimeField(auto_now_add=True)
    edited_at = models.DateTimeField(auto_now=True)
    is_private = models.BooleanField(default=False)

    # post = models.ForeignKey("airsoft_teams.Post", on_delete=models.PROTECT)
    # team_request = models.ForeignKey("airsoft_teams.TeamRequest", on_delete=models.PROTECT)

    class Meta:
        permissions = (
            ('g_view_team', 'View_team_guardian'),
            ('g_create_team_post', 'Creat_post_guardian'),
            ('g_team_member_manager', 'Mamber_manager_guardian'),
            ('g_team_vote', 'Team_vote_guardian')
        )

    # def request_handler(self, request, user):
    #     for key, value in request.items():
    #         print(request.POST.items())
    #         print("i am dumb")
    #         print(key)
    #         print(value)
    #
    #     if key == "add_request":\
    #         self.add_request(user)

    def __str__(self):
        return self.name

    if TYPE_CHECKING:
        objects: models.Manager

    def get_absolute_url(self):
        return reverse(f"/teams/{self.pk}")

    def add_request(self, user):
        """move to request make view func """
        if user not in self.members.all():
            TeamRequest.objects.get_or_create(team=self, user=user)
            return self


class TeamRequest(models.Model):
    team = models.ForeignKey("airsoft_teams.Team",
                             on_delete=models.CASCADE,
                             related_name="team_request"
                             )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    # body = models.TextField()
    def __str__(self):
        return self.user.username

    def request_handler(self, key):
        if key == "add":
            self.add_member()
        if key == "refuse":
            self.refuse_request()

    def add_member(self):
        TeamMember.objects.create(user=self.user, team=self.team)
        assign_perm('g_view_team', self.user, self.team)
        assign_perm('g_create_team_post', self.user, self.team)
        assign_perm('g_team_vote', self.user, self.team)
        self.self_delete()

    def refuse_request(self):
        self.self_delete()

    def self_delete(self):
        self.delete()


# lets do this shit
# vk looks post sys
class TeamPost(models.Model):
    team = models.ForeignKey("airsoft_teams.Team",
                             on_delete=models.CASCADE,
                             related_name="team_post",
                             blank=False,
                             null=True
                             )
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL,
                                   on_delete=models.PROTECT,
                                   related_name="post_by_user"
                                   )
    created_at = models.DateTimeField(auto_now_add=True)
    edited_at = models.DateTimeField(auto_now=True)
    body = models.TextField()
    # imgs = (for add user pic)
    # avatar_of_user = (link to avatar \for opt and dont qs user each time )

# class TeamPostComment(models.Model):
#     post = models.ForeignKey("airsoft_teams.TeamPost",
#     on_delete=models.CASCADE, related_name="team_comment")
#     created_by = models.ForeignKey(settings.AUTH_USER_MODEL,
#     on_delete=models.PROTECT, related_name="comment_by_user")
#     created_at = models.DateTimeField(auto_now_add=True)
#     edited_at = models.DateTimeField(auto_now=True)
#     body = models.TextField()
#     # imgs = (for add user pic)
#     # avatar_of_user = (link to avatar \
#     for opt and dont qs user each time )


# class Members(models.Model):
#     FRIEND = 1
#     MEMBER = 2
#     MANAGER = 3
#     OWNER = 4
#     ROLE_CHOICES = (
#         (FRIEND, 'friend'),
#         (MEMBER, 'member'),
#         (MANAGER, 'manager'),
#         (OWNER, 'owner'),
#
#     )
#     team = models.ForeignKey("airsoft_teams.Team",
#     on_delete=models.CASCADE, related_name="team_members")
#     user = models.ForeignKey(settings.AUTH_USER_MODEL,
#     on_delete=models.CASCADE, related_name="team_profile",)
#     created_at = models.DateTimeField(auto_now_add=True)
#     edited_at = models.DateTimeField(auto_now=True)
#     role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES,
#     default=FRIEND)
#     main = models.BooleanField(default=False)
# chek if user in many teams
#     # role = models.ForeignKey("airsoft_teams.Role",
#     on_delete=models.SET_NULL, null=True)


# def __str__(self):
#     return self.user.username
#
# def request_handler(self, key, value):
#     if key == "role":
#         self.set_role(role=value)
#         return self
#     # if key ==
#
# def set_owner(self, team):
#     self.role = 4
#     self.main = True
#     self.save()
#     # self.user.
#     return self
#
# def set_role(self, role):
#     self.role = role
#     self.save()
#     return Members
#
# def promote(self):
#     if self.role < 4:
#         self.role=self.role + 1
#         self.save()
#         return self
# def depromote(self):
#     if self.role > 1:
#         self.role = self.role - 1
#         self.save()
#         return self

airsoft/airsoft_teams/forms.py
# pylint: disable=too-many-ancestors
# pylint: disable=missing-module-docstring
# pylint: disable=missing-class-docstring
# pylint: disable=missing-function-docstring


from django import forms

from airsoft_teams.models import TeamPost


class TeamPostForm(forms.ModelForm):
    # template_name = "team_post_create.html"
    class Meta:
        model = TeamPost
        fields = ["body", ]

airsoft/airsoft_teams/templates/team_create.html
{% extends 'homepage/base.html' %}

{% block title %}
Creat Team2

{% endblock %}

{% block body %}
<form method="post" >
    {% csrf_token %}
    {{ form.as_p }}

    <button class="btn btn-outline-secondary btn-sm" type="submit" name="team" value="team" >Creat</button>
     <a href="{% url 'airsoft_teams:teams' %}" class="btn btn-outline-secondary btn-sm">Back</a>
</form>

{% endblock %}

{% block content %}




{% endblock %}

airsoft/airsoft_teams/templates/team_details.html
{% extends 'homepage/base.html' %}




{% block body %}
<p>team :</p>

{{user.team_profile.role}}

<li class="list-group-item">name - {{team.name}}</li>
<li class="list-group-item">city - {{team.city}}</li>
<li class="list-group-item">description - {{team.description}}</li>

<li class="list-group-item">id - {{team.id}}</li>
<li class="list-group-item">created_at - {{team.created_at}}</li>
<li class="list-group-item">edited_at - {{team.edited_at}}</li>
<li class="list-group-item">is_private - {{team.is_private}}</li>
<img src={{ team.chevron.url }}>

<form method="post"> {% csrf_token %} <button class="btn btn-outline-primary btn-sm" name="add_request" value="add_request" type="submit"> request </button></form>



{% endblock %}

airsoft/airsoft_teams/templates/team_manger.html
{% extends 'homepage/base.html' %}




{% block title %} some shit{% endblock %}

{% block body %}


{% for team in teams %}
<li class="list-group-item"><a href="{% url 'airsoft_teams:team' team.pk %}">{{ team.name }}</a></li>

{% endfor %}

{% endblock %}

{% block content %}
<a href="{% url 'airsoft_teams:create' %}" class="btn btn-outline-secondary btn-sm">Create</a>
{% endblock %}

airsoft/airsoft_teams/templates/team_member_details.html
{% extends 'homepage/base.html' %}



{% block body %}
<p>team :</p>
{{user.members}}
{{user.get_role_display}}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
    {% endfor %}
</ul>
{% endif %}

<li class="list-group-item">name - {{team.name}}</li>
<li class="list-group-item">city - {{team.city}}</li>
<li class="list-group-item">description - {{team.description}}</li>

<li class="list-group-item">id - {{team.id}}</li>
<li class="list-group-item">created_at - {{team.created_at}}</li>
<li class="list-group-item">edited_at - {{team.edited_at}}</li>
<li class="list-group-item">is_private - {{team.is_private}}</li>
<img src={{team.chevron.url }}>



<div>
<p><li class="list-group-item">user request</li></p>

    {%for request in team.team_request.all %}
<div>
<form method="post" action="{% url 'airsoft_teams:request_manager' team.id request.id %}" > {% csrf_token %}
    <li class="list-group-item">name - {{ request }}  userid - {{ request.user.id }}  reqID-{{request.id}}</li>

    <button class="btn  btn-outline-secondary btn-sm" name="add" value="{{request.id}}"  type="submit">
        add </button>

    <button class="btn btn-outline-secondary btn-sm" name="refuse" value="{{request.id}}"  type="submit">
        refuse </button>
</form>
</div>
    {%endfor%}
</div>
<div>
{% include "team_members.html" with team_members=team.team_member.all  %}
</div>

<p><li class="list-group-item">Vote list</li></p>
<div>
{% include "vote.html" with votes=team.event_vote.all  %}
</div>



<p><li class="list-group">team_registration</li></p>
{%for reg in team.team_registration.all %}
<li class="list-group-item">Event - {{ reg.event }} </li>
    {%for user  in reg.players.all %}

    <li class="list-group-item"> {{user}} </li>
    {%endfor%}
{%endfor%}





<div class="list-group">
    {%for post in team.team_post.all %}
       <li class="list-group-item"> {{ post.created_by }} - {{post.body}}</li>




    {%endfor%}</div>
<div>
    <form method="post" action="{% url 'airsoft_teams:post_create' team.id %}" >
    {% csrf_token %}
    {{ post_form }}

    <input type="hidden" name="team" value="{{team.id}}">
    <button class="btn btn-outline-secondary btn-sm" type="submit" name="team" value="{{team.id}}" >Creat</button>
     <a href="{% url 'airsoft_teams:teams' %}" class="btn btn-outline-secondary btn-sm">Back</a>
</form>




</div>







{% endblock %}

airsoft/airsoft_teams/templates/team_members.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--team_member-->
<!--{%for member in team_members%}-->

<!--{{member}} {{member.user.id}} {{member.id}}-->
<!--{%endfor%}-->



<p><li class="list-group">Member list</li></p>
{%for member in team_members%}
<li class="list-group-item">user -{{ member.user }} member_id - {{member.id}}  user_id - {{ member.user.id }} created_at -{{member.created_at}} edited -{{member.edited_at}}role - {{member.get_role_display}}</li>


</form>
    <form method="post" action="{% url 'airsoft_teams:member_manager' team.id member.id %}" > {% csrf_token %}
    <button class="btn btn-outline-secondary btn-sm" name="kick" value="{{member.id}}"  type="submit">kick</button>


<div class="dropdown">
  <button class="btn btn-outline-secondary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    choose role
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <button class="btn btn-outline-secondary btn-sm" name="role" value="1"  type="submit">friend </button>
      <button class="btn btn-outline-secondary btn-sm" name="role" value="2"  type="submit">member </button>
      <button class="btn btn-outline-secondary btn-sm" name="role" value="3"  type="submit">manger </button>
      <button class="btn btn-outline-secondary btn-sm" name="role" value="4"  type="submit">owner</button>

  </ul>
</form>
</div>
{%endfor%}


</body>
</html>

airsoft/airsoft_teams/templates/team_post_create.html
{% extends 'homepage/include_base.html' %}




{% block title %}


{% endblock %}



{% block body %}
{{team}}
<form method="post" >
    {% csrf_token %}
     {{ Post_Form }}


    <button class="btn btn-outline-primary btn-sm" name="post" value="{{team}}" type="submit"> post </button>
     <a href="{% url 'airsoft_teams:teams' %}" class="btn btn-outline-secondary btn-sm">Back</a>
</form>
{% endblock %}

{% block content %}

{% endblock %}

airsoft/airsoft_teams/templates/teams.html
{% extends 'homepage/base.html' %}


{%block navbartop%}
{% if user.is_authenticated %}
<div class="col-xs-12 col-md-10">
    <a class="btn btn-outline-secondary btn-sm" href="{% url 'airsoft_teams:create' %}">Create</a>
    {%else%}
    <div class="col-xs-12 col-md-10">
        <a class="btn btn-outline-secondary btn-sm" href="{% url 'u_auth:login' %}">Create</a>
        {% endif%}

        {% endblock %}


        {% block body %}

        <div class="row row-cols-3 row-cols-md-5 g-4">

            <div class="card h-100">
                <img alt="..." class="card-img-top" src="media/nopic.jpeg">
                <div class="card-body">
                    <h5 class="card-title">Creat</h5>
                    <p class="card-text"> Team</p>
                    {% if user.is_authenticated %}
                    <a class="stretched-link" href="{% url 'airsoft_teams:create' %}"></a>
                    {%else%}
                    <a class="stretched-link" href="{% url 'u_auth:login' %}"></a>
                    {% endif%}
                </div>
            </div>

            {% for team in teams %}
            <div class="col">
                <div class="card h-100">
                    <img alt="..." class="card-img-top" src={{ team.chevron.url }}>
                    <div class="card-body">
                        <h5 class="card-title">{{ team.name }}</h5>
                        <p class="card-text">{{ team.description }}</p>
                        {% if user.team_profile.team == team %}
                        <a class="stretched-link" href="{% url 'airsoft_teams:team' team.pk %}"></a>
                        {% else %}
                        <a class="stretched-link" href="{% url 'airsoft_teams:team_view' team.pk %}"></a>
                        {% endif%}
                    </div>
                </div>

            </div>

            {% endfor %}
        </div>

        <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
        </div>
        {% endblock %}

        {% block title %}{% endblock %}


        {% block content %}

        {% endblock %}