airsoft/airsoft/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include("homepage.urls")),
    path("teams/", include("airsoft_teams.urls")),

    path('registration/', include("airsoft_registration.urls")),

    path('organization/', include("airsoft_organization.urls")),
    path('events/', include("airsoft_event.urls")),
    path('shops/', include("airsoft_shops.urls")),
    path("admin/", admin.site.urls),
    path('auth/', include("u_auth.urls")),


    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




# admin if debug
if settings.DEBUG:
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

airsoft/airsoft_organization/urls.py
from django.urls import path

from airsoft_event.views import EventCreateViews
from .views import OrgListView, OrgCreate, OrgDetails

app_name = "airsoft_organization"
urlpatterns = [
    path("", OrgListView.as_view(), name="orgs"),
    path("create/", OrgCreate.as_view(), name="org_create"),
    path("<int:pk>/", OrgDetails.as_view(), name="org_details"),
    path("<int:pk>/create/", EventCreateViews.as_view(), name="create_event"),


    ]

airsoft/airsoft_teams/urls.py
# pylint: disable=too-many-ancestors
# pylint: disable=missing-module-docstring
# pylint: disable=missing-class-docstring
# pylint: disable=missing-function-docstring
from django.urls import path

from . import views
from .views import TeamListView, TeamCreate, TeamDetails, PostCreateView, TeamMemberDetails

app_name = "airsoft_teams"
urlpatterns = [
    path("", TeamListView.as_view(), name="teams"),
    path("create/", TeamCreate.as_view(), name="create"),
    path("<int:pk>/", TeamMemberDetails.as_view(), name="team"),
    path("<int:pk>/view", TeamDetails.as_view(), name="team_view"),
    path("<int:pk>/post/", PostCreateView.as_view(), name="post_create"),

    path('<int:team_pk>/member_manager/<int:member_pk>/',
         views.member_manager,
         name='member_manager'),

    path('<int:team_pk>/request_manager/<int:request_pk>/',
         views.request_manager,
         name='request_manager'),

]

airsoft/u_auth/urls.py
# pylint: disable=too-many-ancestors
# pylint: disable=missing-module-docstring
# pylint: disable=missing-class-docstring
# pylint: disable=missing-function-docstring
from django.urls import path

from .views import (
    MeView,
    LoginView,
    LogoutView,
    UserCreateView
    )

app_name = "u_auth"

urlpatterns = [

    path("me/", MeView.as_view(), name="me"),
    # path("me/edit", MeView.as_view(), name="me"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register", UserCreateView.as_view(), name="register")

]

airsoft/airsoft_organization/models.py
from typing import TYPE_CHECKING

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.shortcuts import get_object_or_404
# Create your models here.
from django.urls import reverse

UserModel: AbstractUser = get_user_model()


class Organization(models.Model):
    name = models.CharField(max_length=64, blank=False, null=False, unique=True)
    city = models.CharField(max_length=64, blank=True, null=False)
    description = models.TextField()
    logo = models.ImageField(upload_to="org_logo", blank=True, default='nopic.jpeg')
    members = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                     through="airsoft_organization.Member",
                                     related_name="org_member")
    created_at = models.DateTimeField(auto_now_add=True)
    edited_at = models.DateTimeField(auto_now=True)
    is_private = models.BooleanField(default=False)

    if TYPE_CHECKING:
        objects: models.Manager

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(f"/organization/{self.pk}")

    def request_handler(self, request, user):
        for key, value in request.POST.items():
            print(request.POST.items())
            print('Key:', key)
            print('Value', value)
        if key == "add_request":
            self.send_request(user=user)

        if key == "add":
            self.add_member(org_request=get_object_or_404(OrgRequest, pk=value))

        if key == "refuse":
            self.refuse_request(org_request=get_object_or_404(OrgRequest, pk=value))

        if key == "kick":
            self.kick_member(user=get_object_or_404(UserModel, pk=value))

    def can_create_event(self, member):
        print("user role =", member.role)
        if member.role == 4:
            return True

    # def self_org(self, user):
    #     if user == self.owner:
    #         return self.objects

    def send_request(self, user):
        if user not in self.members.all():
            OrgRequest.objects.get_or_create(team=self, user=user)


    def user_in_org(self, user):
        if user in self.members.all():
            return True


    def add_member(self, org_request):
        if org_request.user not in self.members.all():
            self.members.add(org_request.user)
            self.save()
            org_request.self_delete()


    @staticmethod
    def refuse_request(org_request):
        org_request.self_delete()


    def kick_member(self, user):
        self.members.remove(user)
        self.save()



# edit roles for org
class Member(models.Model):
    FRIEND = 1
    MEMBER = 2
    MANAGER = 3
    OWNER = 4
    ROLE_CHOICES = (
        (FRIEND, 'friend'),
        (MEMBER, 'member'),
        (MANAGER, 'manager'),
        (OWNER, 'owner'),

    )
    org = models.ForeignKey("airsoft_organization.Organization",
                            on_delete=models.CASCADE,
                            related_name="org_members"
                            )
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE,
                                related_name="org_profile"
                                )
    created_at = models.DateTimeField(auto_now_add=True)
    edited_at = models.DateTimeField(auto_now=True)
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, default=FRIEND)

    def __str__(self):
        return self.user.username

    def set_owner(self):
        self.role = 4
        self.save()


    def set_role(self, role):
        self.role = role
        self.save()



class OrgRequest(models.Model):
    org = models.ForeignKey("airsoft_organization.Organization",
                            on_delete=models.CASCADE,
                            related_name="org_request")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

    def self_delete(self):
        self.delete()

airsoft/airsoft_organization/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
# Create your views here.
from django.views.generic import ListView, CreateView, DetailView

from airsoft_organization.models import Organization, Member

# Create your views here.

UserModel: AbstractUser = get_user_model()


class OrgCreate(CreateView):
    template_name = "organization_create.html"
    context_object_name = "org"
    # success_url =
    model = Organization
    # form_class =
    fields = ["name", "city", "description", "logo", "is_private"]

    def form_valid(self, form):
        user = self.request.user
        # user_in_team = Team.objects.filter(members=user)
        # if len(user_in_team) == 1:
        #     return HttpResponseRedirect("/teams/create/")
        # else:
        #     # go = None  # optio
        obj = form.save(commit=False)
        obj.save()
        obj.members.add(user)
        form.save_m2m()
        org_member = get_object_or_404(Member, user=user, org=obj)
        Member.set_owner(org_member)
        return HttpResponseRedirect(f"/organization/{obj.id}")


class OrgListView(ListView):
    paginate_by = 14
    context_object_name = "orgs"
    template_name = "organizations.html"
    queryset = (Organization
                .objects
                # .select_related()
                # .prefetch_related()
                .all())


class OrgDetails(DetailView):
    template_name = 'organization_details.html'
    context_object_name = "org"

    queryset = Organization \
        .objects \
        .prefetch_related("org_request", "org_members", "event_owner") \
        .select_related()

    # Move to user manger  (mby use in include templates?)
    # def get_form_kwargs(self):
    #     kwargs = super(self).get_form_kwargs()
    #     kwargs['request'] = self.request
    #     return kwargs

    def post(self, request, *args, **kwargs, ):
        if request.method == 'POST':
            group = get_object_or_404(Organization, pk=self.kwargs["pk"])
            group.request_handler(request=request, user=self.request.user)
            return HttpResponseRedirect(f"/organization/{group.id}")

airsoft/airsoft_organization/templates/organization_create.html
{% extends 'homepage/base.html' %}

{% block title %}
Creat Team

{% endblock %}

{% block body %}
<form method="post" >
    {% csrf_token %}
    {{ form.as_p }}

    <button class="btn btn-outline-secondary btn-sm" type="submit" name="team" value="team" >Creat</button>
     <a href="{% url 'airsoft_teams:teams' %}" class="btn btn-outline-secondary btn-sm">Back</a>
</form>

{% endblock %}

{% block content %}




{% endblock %}

airsoft/airsoft_organization/templates/organization_details.html
{% extends 'homepage/base.html' %}


{% block title %}
Organization
{% endblock %}

{% block body %}
<p>Organization :</p>
<li class="list-group-item">city - {{org.city}}</li>
<li class="list-group-item">описание - {{org.description}}</li>
<li class="list-group-item">name - {{org.name}}</li>
<li class="list-group-item">owner - {{org.owner}}</li>
<li class="list-group-item">id - {{org.id}}</li>
<li class="list-group-item">id - {{org.created_at}}</li>
<li class="list-group-item">id - {{org.edited_at}}</li>
<li class="list-group-item">id - {{org.is_private}}</li>
{{team.user_group.members}}













<p><li class="list-group-item">user request</li></p>
<form method="post"> {% csrf_token %}
{%for request in org.org_request.all %}
<li class="list-group-item">{{ request }}  {{ request.id }}</li>

    <button class="btn  btn-outline-secondary btn-sm" name="add" value="{{request.id}}"  type="submit">
        add </button>

    <button class="btn btn-outline-secondary btn-sm" name="refuse" value="{{request.id}}"  type="submit">
        refuse </button>
</form>
{%endfor%}


<p><li class="list-group-item">Member list</li></p>
<form method="post"> {% csrf_token %}
{%for member in org.membership.members.all %}
<li class="list-group-item">{{ member }}</li>
    <form method="post"> {% csrf_token %}
    <button class="btn btn-outline-secondary btn-sm" name="kick" value="{{member.id}}"  type="submit">
        kick </button>
</form>
{%endfor%}



<a href="{% url 'airsoft_organization:create_event' org.pk  %}" class="btn btn-outline-secondary btn-sm">Create event</a>
<form method="post"> {% csrf_token %} <button class="btn btn-outline-primary btn-sm" name="add_request" value="add_request" type="submit"> request </button></form>

    {% endblock %}

airsoft/airsoft_organization/templates/organizations.html
{% extends 'homepage/base.html' %}


{% block title %}
teams
{% endblock %}

{% block body %}
<div class="row row-cols-3 row-cols-md-5 g-4">
<a href="{% url 'airsoft_organization:org_create' %}" class="btn btn-outline-secondary btn-sm">Create</a>
    {% for org in orgs %}
<div class="col">
    <div class="card h-100">
      <img src={{ org.logo.url }} class="card-img-top" alt="">
      <div class="card-body">
        <h5 class="card-title">{{org.name }}</h5>
        <p class="card-text">{{ org.description }}</p>
      <a class="stretched-link" href="{% url 'airsoft_organization:org_details' org.pk %}"></a>
      </div>
    </div>

</div>
{% endfor %}
</div>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}